name: Test Workflow

on:
  push:
    branches:
      - main
      - developer

jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: self-hosted

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v5

      - name: Step 2
        run: echo "Olá, mundo! Este é o nosso primeiro job no GitHub Actions!"

      - name: Step 3
        run: echo "Olá, mundo! Esta é a Step 3"

      - name: Step 4
        run: echo "Olá, mundo! Esta é a Step 4"
